### ISSUE TITLE
Add Unit Tests

### ISSUE THREAD

**Issue by msheldon83** [plopjs/plop#159]
We should be able to add some unit tests to the CLI project using libraries like 
https://github.com/caitp/node-mock-stdin (or this abstraction https://github.com/bahmutov/bdd-stdin/blob/master/index.js) 
and
https://sinonjs.org/releases/latest/mocks/

**Comment by crutchcorn** [comment]
@msheldon83 do you have a branch that you've been able to cut for this work? Maybe someone else could pickup the work you'd started on?

**Comment by crutchcorn** [comment]
We opted for E2E tests instead, which we now have!
