### ISSUE TITLE
Allow `prompts` to be an async function

### ISSUE THREAD

**Issue by valerybugakov** [plopjs/plop#165]
Hey, first of all, thanks for the awesome library!

It seems we've stumbled into the issue with backward compatibility. Before introducing `bypass prompts`, it was possible to pass an async function as `prompts` into `setGenerator` function. It allowed creating more complex generators where each prompt could reuse answers from the previous one. 

This API [is supported](https://github.com/amwmedia/node-plop/blob/304c8eb5d571bd4fdb34f6c793fddc1c05f6a43b/src/generator-runner.js#L21) by `node-plop`. Would be cool to keep it in `plop` as well.

**Comment by amwmedia** [comment]
Yep, this was an oversight when implementing `bypass`, it looks to be a pretty simple fix though.

**Comment by ArchiCroc** [comment]
yes, it would be nice to see this functionality restored.   Here's the error message I got when I tried it

> [PLOP] Something went wrong with selecting a generator TypeError: generator.prompts.map is not a function
    at combineBypassData ([...]\npm\node_modules\plop\src\bypass.js:16:40)
    at runGeneratorByName ([...]\npm\node_modules\plop\src\plop.js:49:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)

I just started looking at the source code. If you have any pointers on what needs to be changed, I can work on a pull request.

**Comment by amwmedia** [comment]
@ArchiCroc it might be as simple as checking if `generator.prompts` is a function and returning an empty array [in bypass.js](https://github.com/amwmedia/plop/blob/master/src/bypass.js#L16).

**Comment by amwmedia** [comment]
released with v2.5.0
