### ISSUE TITLE
Async data fetching inside actions

### ISSUE THREAD

**Issue by balanza** [plopjs/plop#172]
Hi, 

I don't actually know if this behaviour is wanted or not. My use case implies that the user specify an url for a json as input, then in the actions files are generated based on specifications found in such remote file.

Thus, I need to perform async fetching before returning the action array. I guessed I could just write the following:

``` js
plop.setGenerator({
  prompt: [ /* questions */ ],
  actions: async (data) => {
    const remoteSpec = await fetch(data.specUrl); 
    return [
      {
        type: 'add',
        path: '../dist/test.js',
        templateFile: 'plop-templates/test.hbs',
        data: remoteSpec
      }
    ];
  }
});
```

But the prompt is throwing `⠋ [ERROR] controller has invalid actions`. 

How can I implement such case? I can work it around, but I wonder if plop api already dealt with  async actions generation.

Thanks

**Comment by amwmedia** [comment]
this is something that we could support. However, if you move the fetching into a [custom action function](https://plopjs.com/documentation/#custom-action-function-), you will be able to perform async actions.

**Comment by tomdev10** [comment]
@amwmedia please can you provide some documentation on how to do this? I'm fetching data from a custom action function, and wanting to pass it into a template via an `add` function afterwards - is this possible? Happy to provide code samples.

Effectively need to:

- Fetch a JSON object
- Manipulate this
- Inject it into a template

Any help really appreciated, cheers!

**Comment by amwmedia** [comment]
The custom action function receives the `answers` object as the first parameter. You can actually mutate that object inside the function, and future actions will get those mutations. So you should be able to just tack another property onto that object, and reference it in your add action like you would the other prompt data.

**Comment by tomdev10** [comment]
Brilliant, thank you. I have tried this and it does work. Thank you very much 😊
