### ISSUE TITLE
[enhancement] Support EJS

### ISSUE THREAD

**Issue by ceefour** [plopjs/plop#176]
[EJS](https://ejs.co/) can be alternative templating language

**Comment by benmvp** [comment]
I brought this up a while ago here: https://github.com/plopjs/plop/issues/10#issuecomment-353440006. The idea would be to make the templating language configurable. I tried working on it, but the code is pretty tied to how handlebars works and I didn't completely understand it all, so I moved on. EJS would be so much better IMO for more complex templates

**Comment by dy** [comment]
Yes, especially conditionals. SVG rendering - things like `{{#if align == 1}}` - precalculating every possible micro-expression is pain.

**Comment by crutchcorn** [comment]
Closing in favor of Closing in favor of #10, which describes the method of which we'd implement EJS support
