### ISSUE TITLE
Errors using TypeScript

### ISSUE THREAD

**Issue by julianomqs** [plopjs/plop#179]
Hello,

I'm trying to use plop with TypeScript, and I'm getting some errors.

My `plopfile.ts`

```typescript
import { NodePlopAPI } from "plop";

export default function(plop: NodePlopAPI) {
    // controller generator
    plop.setGenerator("controller", {
        description: "application controller logic",
        prompts: [
            {
                type: "input",
                name: "name",
                message: "controller name please"
            }
        ],
        actions: [
            {
                type: "add",
                path: "src/{{name}}.js",
                templateFile: "plop-templates/controller.hbs"
            }
        ]
    });
}
```

The errors:

`Module '"./node_modules/plop/src/plop"' has no exported member 'NodePlopAPI'.ts(2305)`

Apparently the `NodePlopAPI` is in the `node-plop` module, not in the `plop` module.

And if I change the import from `plop` to `node-plop` I get the following error in the `actions` array:

```
(property) ActionConfig.type: string
Type '{ type: string; path: string; templateFile: string; }' is not assignable to type 'ActionType'.
  Type '{ type: string; path: string; templateFile: string; }' is missing the following properties from type 'AppendActionConfig': pattern, unique, separator, template, and 3 more.ts(2322)
```

Some prints:

![image](https://user-images.githubusercontent.com/7409904/67121501-09b02900-f1c2-11e9-92d8-ed4f0ae72809.png)

![image](https://user-images.githubusercontent.com/7409904/67121529-16348180-f1c2-11e9-8378-21d939b77ea2.png)

**Comment by amwmedia** [comment]
sorry about that, try v2.5.2. Should be fixed
