### ISSUE TITLE
[Request] Update example of plopfile.js and add append to first line of file

### ISSUE THREAD

**Issue by wecarrasco** [plopjs/plop#181]
Hello! I'm in love with this project, but I request two things:

First: In the example of ```plopfile.js```, on lines ```110``` to ```120``` where you are using the action Modify, you use the patterns for ```APPEND HERE``` and ```PREPEND HERE```, but there is no documentation of how it differ if it needs to append or prepend.

Second: It could be nice to have an option on append action to add the template to the first line of the file or in the end of file.

**Comment by dandocse** [comment]
Hi @wecarrasco ,

I found a solution, it can help you to append wherever you want, that solution using a pattern.
First, you need to add a comment to the file you want append
<img width="392" alt="Screen Shot 2021-09-09 at 01 25 30" src="https://user-images.githubusercontent.com/11873241/132564371-dafa7adb-5ae0-4069-a2db-38101e3ab2ad.png">
For ex: I added a comment //appendHere

In the plopfile.js, add into the actions:
{
  type: 'append',
  path: 'src/Store/{{path}}/index.js', // replace your path file you need to append
  pattern: /(\/\/appendHere\s)/g, // keep this line - the template will append bellow your comment
  template: "import {{camelCase name}} from './{{camelCase name}}'", // replace your append template here
}

The result
<img width="552" alt="Screen Shot 2021-09-09 at 01 29 42" src="https://user-images.githubusercontent.com/11873241/132565013-8a372674-577f-4515-8591-f82cb8d6add1.png">

Hope it can help you

**Comment by sandersonsoares** [comment]
Nice! Work for me!

**Comment by Dachak** [comment]
Would be nice to have a prepend action

**Comment by crutchcorn** [comment]
Closing in favor of #336, which documents the intended feature request of a `prepend` action (it was a bit hard to find the actual request here)
