### ISSUE TITLE
Add a debug flag

### ISSUE THREAD

**Issue by jared-hexagon** [plopjs/plop#185]
## Issue

I had an error in my handlebars template for my "add" action (too many curly brackets) but had no way to know what my error was without going through it line by line.

## Proposed solution

Add a "debug" flag to either individual actions or the entire library when you initialise it.

When turned on, it will output basic debugging info (eg. "running "add" action X...") and when an error occurs (like failing to parse or compile handlebar templates) it shows the error. Same with warnings I guess.

**Comment by Akiyamka** [comment]
I think it will be much better if `debug: true` flag run plop in `node --inspect` mode

**Comment by crutchcorn** [comment]
Closing in favor of #323, since it describes exactly what this one does but with a bit more detail
