### ISSUE TITLE
Plop templates in package.json

### ISSUE THREAD

**Issue by tvvignesh** [plopjs/plop#187]
Hi. If we put templates within `package.json` and have plop `modify` it like this:

```
{
    "name": "{{appName}}",
    "version": "{{appVersion}}"
}
```

It fails when I do `npm run plop` since the json is not syntactically correct as per npm validations. I have to rather run `plop` to get the generator working (not via npm). Any ideas on how we can bypass or skip this error triggered by validations in npm and still have plop run through npm?

Thanks.

**Comment by amwmedia** [comment]
I don't think plop can do anything about the npm validations directly as it sounds like you're asking npm to run plop and the error is occurring before plop is even initialized. If you can give more information about what you're trying to accomplish, we might be able to help.
