### ISSUE TITLE
Latest version of plop gives strange errors in react application

### ISSUE THREAD

**Issue by sarita-kumari-dev** [plopjs/plop#190]
I was having plop version 2.1.0 in my application.
During App scan I found some issues of security vulnerabilities which were related to handlebars packages. Since the parent of handlebars was plop hence I tried to update plop package to the latest 2.5.3 and then started to get some issues - 

Error: ENOENT: no such file or directory, open 'D:\home\vcap\app\server\certs\IBMid\blueid-server.crt'
    at Object.openSync (fs.js:443:3)

There is no path which is specified above.
Kindly look into it and send updates on the same.

**Comment by amwmedia** [comment]
Have you tried removing your node_modules folder and reinstalling? To my knowledge, plop does not use any file that would be at the path described here.

**Comment by Sarita-persi** [comment]
Hi,

Yes I tried with removing node_modules folder and did npm install number of times. Plop package is acting as super parent of handlebars which I can see in my package-lock.json file.

Regards,
Sarita Kumari

**Comment by amwmedia** [comment]
are you able to reproduce this issue in a skeleton project that you can upload? The error message doesn't give much helpful information, so the more you can provide, the better.

**Comment by crutchcorn** [comment]
Closing this, since the issue is now 3 years old, and we do not have a minimal repro. Please re-open if you run into the same issue
