### ISSUE TITLE
Is it possible to choose a default case for an input prompt?

### ISSUE THREAD

**Issue by mplis** [plopjs/plop#194]
When using the `input` prompt type, is it possible to set a default case that that input will be in? In my use case, I mostly want the input to be in PascalCase, but I can't guarantee the user will input a value in that case and I'd prefer not to have to have `{{pascalCase componentName}}` everywhere in my templates.

**Comment by crutchcorn** [comment]
As Plop uses [inquirer](https://www.npmjs.com/package/inquirer#separator) under the hood to generate the prompts, you should be able to enforce user input validation using the `validate` property
