### ISSUE TITLE
adding a logo to main site?

### ISSUE THREAD

**Issue by shaun-sweet** [plopjs/plop#196]
Hello!! Our team here at Carvana currently leverages plopjs.  Is there some way to get our logo added to the list of companies using this excellent tool?

**Comment by crutchcorn** [comment]
If possible, please reopen this ticket under the following repo for better tracking:

https://github.com/plopjs/plopjs.com

**Comment by amwmedia** [comment]
short answer, yes! ;-)

**Comment by amwmedia** [comment]
Also... how did you know I was car shopping!? These new advertising algorithms are amazing!
