### ISSUE TITLE
Async actions function

### ISSUE THREAD

**Issue by zonzujiro** [plopjs/plop#197]
Hey!

I need to implement the next logic - if file exists - use `modify` action and if not - `add`.

```javascript
actions: async data => {
  const actions = [];
  const shouldModify = await isFileExist("some-path");

  if (shouldModify) {
    actions.push({
      type: "modify"
    });
  } else {
    actions.push({
      type: "add"
    });
  }

  return actions;
};
```

I know, that I can use custom actions to perform the async operation. But in such a case, I will need to create or modify the file by myself, which I don't want to do.

I just want to decide what action I should use and not implement action on my own.

From what I see, right now this is something which impossible to do. But maybe I am mistaking and it is possible to do? Maybe some pattern which I lose? :)

**Comment by zonzujiro** [comment]
I will just use `accessSync`. No need for such "improvements" :)

**Comment by amwmedia** [comment]
Yes, I agree, we should be able to use an `async` functions as an `DynamicActionsFunction`. This should actually be pretty easy to do.
