### ISSUE TITLE
How to print custom message from custom action

### ISSUE THREAD

**Issue by Akiyamka** [plopjs/plop#198]
Sometimes i need output some info from custom action to console for debug proposes , but console.log not print anything if it called inside action. How i can solve this?

**Comment by amwmedia** [comment]
A returned string will be shown as the status message for the action function. If you need more granular data, you could consider breaking your action function into multiple functions.

**Comment by Akiyamka** [comment]
I found another dirty workaround - add to actions `log` property.
```js
{
  type: 'myCustomAction',
  ...,
  log: message => console.log(message)
}
```

**Comment by crutchcorn** [comment]
Closing since there appears to be a workaround, and it's not clear what an alternative API might look like
