### ISSUE TITLE
How to apply multiple case modifiers?

### ISSUE THREAD

**Issue by damianof** [plopjs/plop#200]
How to apply multiple case modifiers?

**Comment by datner** [comment]
https://handlebarsjs.com/guide/expressions.html#subexpressions

this a handlebars question, not a plop question, but anyways
```handlebars
{{pascalCase (kebabCase name) }}
```
should do the trick. Not really sure though why you would want to stack them, since they cancel out

**Comment by damianof** [comment]
I did not they did cnacel out, my bet. Thank you for your time.
