### ISSUE TITLE
the import of anything that isn't a generator using plop.join fails if you use esm

### ISSUE THREAD

**Issue by datner** [plopjs/plop#201]
Let's say I have the following plopfile

```js
module.exports = plop => {
  plop.setWelcomeMessage(
    'Welcome to otoPlop! What otoType of otoFile do you otoWant? 🚗 🤔'
  )
  plop.load('./plop-files/generators/helpers', {}, { helpers: true })
  plop.load('./plop-files/generators/redux-module', {}, { helpers: true, generators: true })
  plop.load('./plop-files/generators/component')
  plop.load('./plop-files/generators/generator')
}
```

and all my generators are exported from their own index using esm like so:
```js
const esmRequire = require('esm')(module)

module.exports = esmRequire('./component').default
```

from what I gather, the `helpers` (which only hold helpers) should give their helpers to any subsequent plopfiles, and `redux-module` should have its generators **and** helpers registered.
but while the generators are registered, the helpers are not exposed outside of their original plopfiles. I looked through `plop-node` and it looks like the generators are being registered in a slightly different way than all the others, which makes it a possible spot where it breaks

Any ideas?

**Comment by amwmedia** [comment]
if `redux-module` needs to use `helpers`, then it would need to `plop.load` the helpers in directly. This is creating nested contexts, not modifying a single shared context.

**Comment by crutchcorn** [comment]
This should now be solved with `node-plop` and `plop` both using ESM since `0.30.0` and `3.0.0` respectively
