### ISSUE TITLE
How I can use bottom bar from inquirer api?

### ISSUE THREAD

**Issue by Akiyamka** [plopjs/plop#203]
Inquirer have feature - write message to bottom bar. I want put tooltips in bottom bar, but I cant' find how i can call `new inquirer.ui.BottomBar() from plop. Any ideas?
```js
const ui = new inquirer.ui.BottomBar();

// pipe a Stream to the log zone
outputStream.pipe( ui.log );

// Or simply write output
ui.log.write("something just happened.");
ui.log.write("Almost over, standby!");
```
http://adilapapaya.com/docs/inquirer/#bottombarinquireruibottombar

**Comment by amwmedia** [comment]
You can access the `inquirer` API directly at `plop.inquirer` inside of a plopfile.

example:
``` javascript
module.exports = function (plop) {
  const ui = new plop.inquirer.ui.BottomBar();
  ...
}
```

I have not verified that there are no issues with using things like BottomBar with plop, but that would be how you would go about accessing the inquirer instance that plop is using.
