### ISSUE TITLE
plop strip off the `undefined` keyword while using the `modify` action

### ISSUE THREAD

**Issue by 3dos** [plopjs/plop#205]
This is a bug when using the `modify` action on a file containing the `undefined` keyword, said keyword is stripped off of the provided code.

simple reproducible example:

```ts
// src/fileWithUndefinedInIt.ts

type SomeType = string | undefined; // undefined will disappear

/* some code... blah blah */
```
and the plopfile

```js
// plopfile.js

module.exports = function(plop) {
  plop.setGenerator("example", {
    description: 'demonstrate the "undefined" bug',
    prompts: [],
    actions: [
      {
        type: "modify",
        path: "src/fileWithUndefinedInIt.ts",
        transform: code => {
          console.log(code); // logs out => type SomeType = string | ; //  will disappear
          return code;
        }
      }
    ]
  });
};
```

The expected result is obviously to keep the `undefined` keywords into the provided code.

plop version used: 2.6.0

**Comment by amwmedia** [comment]
@jacksteamdev any idea why this might be happening with the transform function?

**Comment by jacksteamdev** [comment]
I'll try to get a PR together soon.

Looks like this is happening [here](https://github.com/plopjs/node-plop/blob/8c39295c33130a57ee6cf9841d5fe8bfc6a0e818/src/actions/modify.js#L29):

```js
fileData = fileData.replace(cfg.pattern, replacement);
```

When the action `pattern === undefined`, JS tries to help and converts it to the string `"undefined"`, thus removing the word "undefined" from the file.

A quick workaround would be to set the pattern to an empty string:

```
// plopfile.js

module.exports = function(plop) {
  plop.setGenerator('example', {
    description: 'demonstrate the "undefined" bug',
    prompts: [],
    actions: [
      {
        type: 'modify',
        path: 'test.ts',
        transform: (code) => {
          console.log(code)
          return code
        },
        pattern: '' // an empty string
      },
    ],
  })
}
```
