### ISSUE TITLE
Bypassing named arguments does not work when called from yarn

### ISSUE THREAD

**Issue by KnisterPeter** [plopjs/plop#207]
When I want to use `plop` with `yarn` its not possible to bypass prompts by name. This is caused by `yarn` removing the double dash and echoing a notice.

For example running this will prompt the user:
```shell
$ yarn plop -- --name "some-name"
```

In this case what plop receives from `yarn` is:

```shell
$ plop --name "some-name"
```

Is there another separator which could act as the double dash?

**Comment by amwmedia** [comment]
Not that I know of. You could use standard bypass (not by named parameter), but this is really just a side effect of how yarn interprets and uses the double dash.
