### ISSUE TITLE
Feature Request: Update Prompts to support Inquirer reactive-interface

### ISSUE THREAD

**Issue by jrobber** [plopjs/plop#211]
It would be awesome if Plop exposed the reactive-interface that Inquirer is using.
It looks like Plop is using it underneath.  How hard would it be to expose it?

https://github.com/SBoudrias/Inquirer.js/#reactive-interface

**Comment by amwmedia** [comment]
It's not well documented, but this is currently supported. https://github.com/plopjs/plop/issues/81

**Comment by crutchcorn** [comment]
Closing, since there's a larger discussion to be had about documentation in general, and I'd like to keep the docs convo in a newer project/thread
