### ISSUE TITLE
Plop continues to use deprecated components

### ISSUE THREAD

**Issue by ssanbeg** [plopjs/plop#212]
This has been going on awhile, and the deprecations have been out for awhile. Please update your code.

macOS 10.14.6 Mojave

   npm install --save-dev plop
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated @types/globby@9.1.0: This is a stub types definition. globby provides its own type definitions, so you do not need this installed.
npm WARN deprecated @types/handlebars@4.1.0: This is a stub types definition. handlebars provides its own type definitions, so you do not need this installed.

**Comment by crutchcorn** [comment]
This is no longer the case with v3
