### ISSUE TITLE
Using plop programmatically

### ISSUE THREAD

**Issue by Troncoso** [plopjs/plop#214]
I am building a cli tool that generates code in a very specific way. Essentially, I have a configuration file and I need to add/update code in accordance with that configuration. I would like to use Plop as the engine for the code generation part, but it seems designed specifically to be used from the CLI.

Can plop be used programmatically such that my application calls on it as needed rather than a user? Obviously I could  use the child_process package to programmatically call the plop CLI, but I was hoping I could just directly command plop from my code.

**Comment by crutchcorn** [comment]
Plop _can_ be called programmatically. For example, I'm wrapping `plop` into my own code editor for a project for work:

```javascript
#!/usr/bin/env node
const path = require('path');
const args = process.argv.slice(2);
const {Plop, run} = require('plop');
const argv = require('minimist')(args);

Plop.launch({
  cwd: argv.cwd,
  configPath: path.join(__dirname, 'plopfile.js'),
  require: argv.require,
  completion: argv.completion
}, run);
```

And then I update my `package.json` to include the `bin` prop:

```json
  "bin": {
    "create-project-app": "./index.js"
  },
```

This just allows you to wrap Plop in another command. However, you can also do things like use the underlying `node-plop`, effectively forking `plop` and using it's template resolution engine for free.

I would suggest reading through the `plop` docs and familiarizing yourself with custom actions and such. I've been able to add "npm install" functionality after code generation and you can do so much more as well:

```javascript
const { spawn } = require('child_process');
const { resolve } = require('path');

module.exports = function(plop) {
  plop.setActionType('npmInstall', function(answers, config, plop) {
    return new Promise((resolve, reject) => {
        const ls = spawn('npm', ['install'], {
          cwd: config.path,
          shell: true
        });

        ls.stdout.pipe(process.stdout);

        ls.stderr.pipe(process.stderr);

        ls.on('close', (code) => {
          resolve(code);
        });
      }
    );
  });
// ...
};
```

**Comment by crutchcorn** [comment]
Documentation on how to do this (wrapping plop in your own CLI) more effectively has been created: 

https://plopjs.com/documentation/#wrapping-plop 

Closing this issue

**Comment by paulfrench** [comment]
I want to use plop programmatically but cannot see how? I'm writing a VSCode extension and would like to use plop to do the code gen, this means creating a single webpack bundle file for the VSCode extension. I'm no javascript or webpack expert etc so any pointers to this would be great. I'm assuming I will need to use some form of webpack file loaders to allow the loading of the plopfile.js and the mustache templates from the webpack bundle?
