### ISSUE TITLE
Plop for react native? function unresolved

### ISSUE THREAD

**Issue by LorenzoLongo** [plopjs/plop#218]
Is it possible to use this framework inside a React-Native app?

If so, I already tried to install and configure the package, but the method setGenerator() stays unresolved for some reason.

```
module.exports = function(plop)  {
    plop.setGenerator('component', {
        description: 'Create a component',
        prompts: [
            {
                type: 'input',
                name: 'name',
                message: 'What is your component name?'
            },
        ],
        actions: [
            {
                type: 'add',
                path: 'src/scenes/screens/{{camelCase name}}/index.js',
                templateFile: 'src/services/dev/plop-templates/index.js.hbs',
            }
        ]
    });
};
```

**Comment by amwmedia** [comment]
Plop is a generic `node` tool and can be used in any type of stack. So yes, this should fine. If you can provide some more information and some reproduction steps, we'd be happy to help you figure out what is going wrong in your case.

**Comment by LorenzoLongo** [comment]
Thank you! I've managed to make it work by reinstalling the node_modules. But I have another question involving the path variable. Is there a way to generate a specific file in the current folder you are in?

**Comment by amwmedia** [comment]
By default, plop bases all paths off the location of the plopfile. However, you can use a helper function to gain access to `process.cwd()` and use that helper in how you define your destination paths.

**Comment by LorenzoLongo** [comment]
Superb, thanks for the help!
