### ISSUE TITLE
NodePlopAPI no export

### ISSUE THREAD

**Issue by eightHundreds** [plopjs/plop#221]
![image](https://user-images.githubusercontent.com/18695431/82791336-215e3700-9ea0-11ea-85a8-6d37882d8d6d.png)

**Comment by amwmedia** [comment]
Summoning the TypeScript wizards... @cspotcode @crutchcorn 

😉

**Comment by cspotcode** [comment]
Looks like `NodePlopAPI` isn't exported.  If that's what you want, then it'll need an `export ` added to it in the declaration file.  Though it's technically an interface, this is all standard ES6 import / export syntax.  Just like you might `export const foo = ...` you can export types via `export interface NodePlopAPI ...`

**Comment by jonathanmorley** [comment]
i think that export needs to be added to https://github.com/plopjs/node-plop/blob/master/types/index.d.ts#L8

**Comment by ryansonshine** [comment]
This issue is still occurring

**Comment by Paden** [comment]
Thanks for adding this. When I do an `npm install node-plop` -- I'll still get the index.d.ts without the export (0.26.0). Any chance in doing a minor release for this?

**Comment by cspotcode** [comment]
Paging the publishing wizard, @amwmedia , any chance of getting a new release published?

**Comment by ryansonshine** [comment]
+1

**Comment by crutchcorn** [comment]
This has now been released in `0.26.1` of `node-plop` and `2.7.1` of `plop`. Apologies for the extreme delay, y'all
