### ISSUE TITLE
TypeScript typing for ActionConfig missing `stripExtensions` (2.7.0)

### ISSUE THREAD

**Issue by johnsantos-wag** [plopjs/plop#225]
Hi,

I think there are some misalignment with the new typings versus in the documentation which serves as the source of truth. This is my existing code

```ts
import { AddManyActionConfig } from 'plop';

export const useAddManyAction = (): AddManyActionConfig => ({
  type: 'addMany',
  base: '',
  templateFiles: '',
  path: '',
  destination: '',
  stripExtensions: ['hbs'],
  globOptions: {
    dot: true
  },
});

```

Then when I installed the latest version `2.7.0` - the typing definition got changed and a lot of things went being required. But, on the website, it is still optional. Can you please give us some migration notes or updates on the release? Thank you.

**Comment by amwmedia** [comment]
@cspotcode @crutchcorn any insight on this?

**Comment by cspotcode** [comment]
My insight is: migrate the codebase to TS. :)

Based on this report, stripExtensions is missing from the relevant interface?

**Comment by amwmedia** [comment]
@cspotcode still waiting for that PR 😉

**Comment by cspotcode** [comment]
Kidding aside, I sent one but @crutchcorn closed it.  I don't remember the details exactly, but I think there'll need to be some agreement before it's resurrected.
https://github.com/plopjs/node-plop/pull/135#issuecomment-624871463

There's also https://github.com/cspotcode/plop

**Comment by amwmedia** [comment]
Yeah, I think I remember seeing that now. I wonder if @johnsantos-wag would mind putting in a PR for this specific issue? Seems like the TS type definitions shouldn't really change often once they stabilize... but who knows.

**Comment by amwmedia** [comment]
@cspotcode @crutchcorn thoughts on moving the types to something like https://github.com/DefinitelyTyped/DefinitelyTyped?

**Comment by cspotcode** [comment]
@jedmao's comments sum up my opinion:
https://github.com/plopjs/node-plop/pull/132#issuecomment-548904384

Especially considering how obvious it is to fix this issue.  There's an interface and it's missing `stripExtensions`.  If we ctrl+f that file, we see that `stripExtensions` isn't mentioned anywhere.  It would take a minute to fix and publish.

**Comment by crutchcorn** [comment]
I stand by my views that this codebase does not need to be in TS. Further, I don't think we need to move the typings. I'll make a PR to have this fixed

**Comment by FDiskas** [comment]
This all project should be refactored to typescript and forget it

**Comment by crutchcorn** [comment]
This issue is fixed in `plop@2.7.4` and `node-plop@0.26.2`

**Comment by FDiskas** [comment]
yes and raised new ones.

**Comment by crutchcorn** [comment]
Please post code sample as text @FDiskas. It will help me debug and ensure that error won't happen again

**Comment by FDiskas** [comment]
I can't

**Comment by FDiskas** [comment]
The working version is
```
node-plop@~0.26.0:
  version "0.26.0"
  resolved "https://registry.yarnpkg.com/node-plop/-/node-plop-0.26.0.tgz#9666b22cd46c7240fec2387e6000d43df8f2104d"
  integrity sha512-jVFKfAIwHcURjk1Gl6wVZ0Csqo5irlOKhdCQppn/yoSUSkHFP4LomMjpO3tUj2ADMlguKbqTEg7LKCi59vDsxg==
```
```
plop@^2.7.1:
  version "2.7.1"
  resolved "https://registry.yarnpkg.com/plop/-/plop-2.7.1.tgz#b48af861f19cb4d5ce141852e4385180419b4b83"
  integrity sha512-2c1CDgi/88AmDNWyQcHILvjFxiyG/nS7CbDUUvzuWdrunW5QUWtQRKJRoITkGNze3ZcpUO9OOGCdh6BxHI+viA==
  dependencies:
    "@types/liftoff" "^2.5.0"
    chalk "^1.1.3"
    interpret "^1.2.0"
    liftoff "^2.5.0"
    minimist "^1.2.0"
    node-plop "~0.26.0"
    ora "^3.4.0"
    v8flags "^2.0.10"
```

**Comment by cspotcode** [comment]
@FDiskas you can send us a code example as text.  Saying "I can't" isn't going to fly since you already send a screenshot.

If you are unwilling to do that, then you should rename your plopfile to .js or otherwise disable typechecking.  You can Google for `// @ts-nocheck` or use type assertions to accomplish this.  This is obviously not ideal; it would be better for you to send us a code example as text so we can identify and fix the issue you are encountering.
