### ISSUE TITLE
How can I preserve handlebar templates in my templates?

### ISSUE THREAD

**Issue by zachsa** [plopjs/plop#227]
One of my templates (a package.json file) includes this line:

```
"prettier:watch": "onchange \"src/**/*.@(js|jsx|css|scss)\" -- prettier --write {{changed}}",
```

When I run plop (I do this via `npm run plop`), this line is replaced with:

```
"prettier:watch": "onchange \"src/**/*.@(js|jsx|css|scss)\" -- prettier --write ",
```

How can I preserve handlebar templates in my templates?

**Comment by zachsa** [comment]
This solved my problem: https://stackoverflow.com/a/20570734/3114742

Handlebars allows escaping like so:

```... \{{ myHandlbarsVar }} ...
```

**Comment by zachsa** [comment]
I think it would be worth adding this to the documentation - I feel like it was a 'lucky' find to see this

**Comment by crutchcorn** [comment]
@zachsa typically I'd argue "it's just handlebars, we should leave the relevant documentation to upstream", but this is far from the first time this question has been asked in this project, so I totally agree that we should document this. Would you be willing to submit a PR for this? :)

**Comment by airtonix** [comment]
It's not just handlebars things... this will come up in standard typescript react files too : 

```tsx
//generators/new/thing/src/{{pascalCase name}}.ts
import * as styles from './{{pascalCase name}}.module.css';

export type {{pascalCase name}}Props = {
  className: string
}
export const {{pascalCase name}}:Reac.FC<{{pascalCase name}}Props> = (props) => (
  <div className={styles.block}>
    <h1 styles={{
      "display": "flex",
      "flexDirection": "column"
    }}>{{name}}</h1>
) 
```

That `styles={{ ... }}` will get interpreted as handlebars.

**Comment by amwmedia** [comment]
Plop will treat every template it processes as a handlebars template. So, when it comes to plop templates, it really is all just handlebars... plop doesn't care what the output is used for.

**Comment by crutchcorn** [comment]
Closing, since there is a lot to be done with documentation, including this. I will re-tag this issue when we've made general progress on the documentation front and contribution is ready to be made
