### ISSUE TITLE
Configure destBasePath explicitly in the wrapper

### ISSUE THREAD

**Issue by vinicius0026** [plopjs/plop#228]
Hi there!

I'm trying to write a cli tool that is basically a wrapper around plop. I've seen issue #214 and also the docs on wrapping plop.

I've followed these instructions, but what I'm missing is this: I want the destination path to be the cwd of the caller of the tool, instead of the using the `plopfile` directory.

I can work around it by setting `passArgsBeforeDashes` to false and then calling the cli tool with `--dest ./`, but that is less than ideal for my use case.

What I'd like to do instead is something like this:

```javascript
#!/usr/bin/env node
const path = require('path');
const args = process.argv.slice(2);
const {Plop, run} = require('plop');
const argv = require('minimist')(args);

const config = {
  cwd: process.cwd(), // use this as destBasePath or
  destBasePath: process.cwd(), // explicitly pass destBasePath here
  configPath: path.join(__dirname, 'plopfile.js'),
  require: argv.require,
  completion: argv.completion
}

Plop.launch(config, env => run(env, undefined, true));
```

I've been looking around the code and that doesn't look like it would work, right? So, I was thinking on augmenting the `env` var that is passed to `Plop.launch` and then try reading `destBasePath` from there, like so:

```javascript
Plop.lauch(config, env => {
  const augmentedEnv = {
    ...env,
    destBasePath: process.cwd() // augment env to include destBasePath
  }
  return run(augmentedEnv, undefined, true);
})
```

And then change the nodePlop instantiation on lines 46-49 on `plop/src/plop.js` to something like this:

```javascript
const destBasePath = argv.dest || env.destBasePath
const plop = nodePlop(plopfilePath, {
	destBasePath: destBasePath ? path.resolve(destBasePath) : undefined,
	force: argv.force === true || argv.f === true || false
});
```

Does this make sense? Is there an easier way to achieve what I want?

Let me know your thoughts and I can open a PR with these changes.

Thank you very much!

**Comment by crutchcorn** [comment]
First off, I definitely appreciate the completeness of this issue. You succinctly outlined the problem, suggested solutions, and were super cool about it. Thanks for that :) 

> I want the destination path to be the cwd of the caller of the tool, instead of the using the plopfile directory.

I guess my question is: Is this not what `destination` prop in the actions would handle? In my own `plop` CLI wrapper, I have code that looks something like this (in the `plopfile.js`):

```javascript
      const kebabName = data.appName.toLowerCase().replace(/\s/g, '-');

      const pathName = `${process.cwd()}/${kebabName}/`;

      actions.push({
        type: 'addMany',
        destination: pathName,
        base: 'template/',
        templateFiles: '**/*',
        globOptions: globOpts
      });
```

And then just use the `pathName` as the `destination` prop in `plopfile.js`. Is there some reason this wouldn't work?

**Comment by vinicius0026** [comment]
@crutchcorn thanks for the prompt answer!

Yeah, I thought of that a minute after posting this issue. It does work and it is fine to close this, but I guess it would be nice to have a way to set that globally instead of having to declare it on each action (helper variables/functions go a long way, as in your example, but perhaps not full-way?)

Anyway, thanks a bunch for this lib, I've been looking for something like this for quite a while, found it yesterday at last!

**Comment by vinicius0026** [comment]
Hey @crutchcorn 

The more I use plop with a wrapper, the more I think having the ability to configure the destBasePath globally (in the wrapper) would be useful.

For one, it allows to still pass `--dest` when calling the tool and override the destination (which would not work with the workaround presented bc the full path is evaluated in the action).

Also, it is error-prone and probably hard to debug for someone creating a new generator that is not aware of this issue.

The tool I'm writing is supposed to be used across our company, by people with varying degrees of familiarity with javascript/node and probably no familiarity at all with plop at the beginning, so it would be very helpful to be able to reduce the surface for errors.

Can you please take this into consideration? If you agree with the solution I drafted in the initial post, I can open a PR with that. If there's a better way, let me know and I also can land a PR.

Thank you!

**Comment by crutchcorn** [comment]
@vinicius0026 the more and more I think about it, the more I agree with you. I'd rather put the onus on plop than the wrapper.

I'd love to accept a PR, go for it!
