### ISSUE TITLE
Transform destination of addMany action

### ISSUE THREAD

**Issue by vinicius0026** [plopjs/plop#230]
Hi there!

I'm using plop wrapped in a custom cli program. I'm trying to use `addMany` action to copy some files and I want to transform the destination path a bit.

Right now, as far as I can tell, the destination path is coupled with the template path. Is there an escape hatch from that?

My templates folder look like this:

```
- templates
| - typescript-package
| | - index.ts.hbs
| | - package.json.hbs
| - javascript-package
| | - index.js.hbs
| | - package.json.hbs
```

And the plopfile looks like this:

```
module.exports = function(plop) {
  plop.setGenerator('typescript-package', {
    prompts: [{
      type: "input",
      name: "name",
      message: "Package name"
    }],
    actions: [{
      type: "addMany",
      templateFiles: "templates/typescript-package/**",
      destination: `${process.cwd()}/{{ dashCase name }}/`
    }]
  })
}
```

The files end up going to `${process.cwd()}/{{ dashCase name }}/typescript-package/**`. I'd like to remove `typescript-package` from the destination, but I want to keep the templates where they are.

Is there an easy way to achieve that? It is similar to the `base` option, but if I use `base` as `"typescript-package/"` it will not find the templates.

If currently there's no way to do this, would you consider a PR (to node-plop) to add a `transformDest` function that will allow transforming the destination path of each file programmatically from the generator declaration?

Thank you!

**Comment by amwmedia** [comment]
There is a `base` property that can be added to the `addMany` config to specify how much of the path should be stripped. I think that should give you what you're looking for.
https://plopjs.com/documentation/#addmany

**Comment by vinicius0026** [comment]
@amwmedia thanks for the prompt response.

I've seen the `base` property, but it strips the path for the templates, not for the destination path. So, if I use `base: "typescript-package/"` in the example above, it will not find the template files (because it will be looking at `templates/`).

A possible solution to be able to manipulate the destination path would be to wrap the path generated here https://github.com/plopjs/node-plop/blob/master/src/actions/addMany.js#L41) with a `transformDest` function that defaults to doing nothing but can be passed in the action options.

```
const transformDest = cfg.transformDest || (d) => d;

// ...

    const fileCfg = Object.assign({}, cfg, {
      path: tranformDest(stripExtensions(cfg.stripExtensions, resolvePath(cfg.destination, templateFile, cfg.base))),
      templateFile: absTemplatePath
    });
```

What do you think?

**Comment by amwmedia** [comment]
Try using `base: "templates/typescript-package/"`. That should limit the templates selected to only files below that path, but it should also strip that path from the destination while dropping the new files.

**Comment by vinicius0026** [comment]
oh, I missed that I needed to include the `template` in the `base` to make it work.

That works, thank you @amwmedia!
