### ISSUE TITLE
Bug: /usr/bin/env: ‘node\r’: No such file or directory

### ISSUE THREAD

**Issue by qianjin1017** [plopjs/plop#232]
version: 2.7.2
system: Linux / MacOS
describe: It's because the file node_modules/.bin/plop has CRLF line endings instead of LF (\r instead of \n) with are Windows line endings.

**Comment by qianjin1017** [comment]
Please fix it! THK

**Comment by qianjin1017** [comment]
You can simply cd to node_modules/.bin/plop
and open plop with vim
vim plop
then you can fix the line endings of the file with
:set ff=unix
then save and quit
:wq
and everything should be fine!

**Comment by crutchcorn** [comment]
Ugh, line endings will never not be the death of me. It's midnight where I am right now, but I will be publishing a release of plop in the morning to fix this. Apologies for the breakage.

**Comment by qianjin1017** [comment]
Thumb up for you



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Corbin Crutchley"<notifications@github.com&gt;; 
发送时间: 2020年7月21日(星期二) 下午2:28
收件人: "plopjs/plop"<plop@noreply.github.com&gt;; 
抄送: "杨小进。。"<763423772@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [plopjs/plop] Bug: /usr/bin/env: ‘node\r’: No such file or directory (#232)





 
Ugh, line endings will never not be the death of me. It's midnight where I am right now, but I will be publishing a release of plop in the morning to fix this. Apologies for the breakage.

**Comment by amwmedia** [comment]
Why would this problem pop up now? @crutchcorn is there something different about how 2.7.2 was built?

**Comment by scerelli** [comment]
The funny thing here is that if you use npm instead of yarn everything works so 

`rm -rf node_modules` `npm install; npm run plop`

**Comment by crutchcorn** [comment]
Kinda, yeah. @amwmedia . I typically have used a Mac for the builds, but just used Windows this time around. Must not have autoclfr configured

**Comment by qianjin1017** [comment]
@crutchcorn  hi, master.   How to create an empty folder in plop？ THK！！！

**Comment by crutchcorn** [comment]
@qianjin1017 please create a new issue for that question. This issue should be resolved as of 2.7.3
