### ISSUE TITLE
 How to create an empty folder in plop？ 

### ISSUE THREAD

**Issue by qianjin1017** [plopjs/plop#234]
What should I do？
THK！！！

**Comment by qianjin1017** [comment]
<img width="789" alt="WeChat550f8171d3f0476d7d99965779d59856" src="https://user-images.githubusercontent.com/19699178/88142670-7b714380-cc28-11ea-97da-576cbc03f362.png">

I think components should be empty folder。

**Comment by qianjin1017** [comment]
@amwmedia

**Comment by qianjin1017** [comment]
@cspotcode

**Comment by qianjin1017** [comment]
@crecotun

**Comment by amwmedia** [comment]
Normally you do not create empty folders with plop. The components folder doesn't need to exist until you plop your first component. If you still feel it's important to create empty folders, you can use a folder with a `.gitkeep` file inside.

**Comment by qianjin1017** [comment]
I did exactly that, thank you！@amwmedia 
Hope that plop is getting stronger and stronger.

**Comment by ndench** [comment]
For anyone else who stumbles across this, you're able to accomplish it with a [custom action](https://www.npmjs.com/package/plop#functionsignature-custom-action)

```javascript
const mkdirp = require('mkdirp');
const path = require('path');

module.exports = function (plop) {
  // ...

  /**
   * Custom action to create an empty folder.
   */
  plop.setActionType('emptyFolder', async function (answers, config, plop) {
    const folderPath = path.resolve(
      plop.getDestBasePath(),
      plop.renderString(config.path, answers),
    );

    await mkdirp(folderPath);

    return folderPath;
  });
};
```
