### ISSUE TITLE
Can I define variable inside actions pattern?

### ISSUE THREAD

**Issue by isuhendro** [plopjs/plop#245]
Hello,

This works with hardcode `pattern` value i.e. `# User field`

``` javascript
    actions: [
      {
        type: "append",
        path: "schema.graphql",
        pattern: `# User field`,
        templateFile: "templates/field.hbs"
      }
    ]
```

But as soon as I changed to below (remove the hardcoded pattern), and enter value = `User` in `model` prompt, the pattern failed to match
``` javascript
    actions: [
      {
        type: "append",
        path: "schema.graphql",
        pattern: `# {{properCase model}} field`,
        templateFile: "templates/field.hbs"
      }
    ]
```

Any suggestion? Thanks in advance

**Comment by dacodekid** [comment]
@isuhendro  I too am stuck on this one.  Have you find any solution ?

**Comment by dacodekid** [comment]
Silly me.  [Here is the solution ](https://plopjs.com/documentation/#using-a-dynamic-actions-array)right on the doc page.  Only thing is that, instead using  `{{ mustache variable }}`, you need to use the `data` parameter to get the value.
