### ISSUE TITLE
Is there a way to use Plop to generate N number of files with 1 template?

### ISSUE THREAD

**Issue by michaelyiu** [plopjs/plop#249]
As per the title, the AddMany action can add multiple files with a single action but seems to generate N number of available templatefiles.

Is there a way where I can generate 20, 50, 100 files with just one template?

**Comment by apowers313** [comment]
I'd just programmatically create an action action for each output file:

plopfile.js:
``` js
fileList = ["one", "zwei", "tres", "quatre", "tano", "roku"];
actionList = fileList.map((fileName) => {
    return {
        type: "add",
        path: fileName,
        templateFile: "templates/myTemplateFile.hbs",
    };
});

module.exports = function (plop) {
	plop.setGenerator('myGenerator', {
		description: 'generator!',
		prompts: [ /* ... * / ],
		actions: actionList
	});
};
```

If you  can programmatically create the fileList, even better...

**Comment by michaelyiu** [comment]
Yeah, that was the path I had to end up taking, thanks!

**Comment by amwmedia** [comment]
yeah, that's what I would have suggested too. If it's a common pattern in your codebase, you could create a custom action to encapsulate the functionality.
