### ISSUE TITLE
Ignore the parsing certain file types

### ISSUE THREAD

**Issue by justinhough** [plopjs/plop#254]
Is there a way with addMany to copy all files, but ignore parsing a set of files with a common extension? 

I am having issues with Laravel Blade templates that fail to complete the task because they also include handlebars in their templating language.

**Example:**
`{{ __('This page doesn't not exist', '404') }}`

**Error Received:**
```
✖  +! Parse error on line 8:
...-warning">      {{ __('Sorry, but the p
----------------------^
Expecting 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'INVALID'
```

**Comment by findxc** [comment]
@justinhough the handlebars provide two ways to escape: https://handlebarsjs.com/guide/expressions.html#escaping-handlebars-expressions

```
\{{escaped}}

or

{{{{raw}}}}
  {{escaped}}
{{{{/raw}}}}
```

**Comment by justinhough** [comment]
@findxc Thanks for the reply. 

The issue is that the errors are coming from the Laravel Blade template files that I don't want to escape. The blade templates should be ignored and just outputted directly without trying to be read for output. If I escape the code in the blade templates then when I compile a new project I would need to unescape all code in order to use the output again.

**Comment by amwmedia** [comment]
If you escape the files that are to be used as templates, the escaping will be process and removed when plop stamps out the new files from the template files. However, if for some reason you need to just copy files without any processing, I suggest using a [custom action function](https://plopjs.com/documentation/#custom-action-function-) that utilizes node's built in [fs.copyFile](https://nodejs.org/api/fs.html#fs_fspromises_copyfile_src_dest_mode) function to copy the appropriate files.

**Comment by crutchcorn** [comment]
Closing, since this API should either be:

- Escaping
- A custom action function
