### ISSUE TITLE
Modify without pattern raises error

### ISSUE THREAD

**Issue by dy** [plopjs/plop#258]
Docs say that in case of _modify_ action `pattern` defaults to _end-of-file_. 
Same time, running it as 
```
,...
    {
      type: "modify",
      path: "masters/wavefont.designspace",
      // pattern: '',
      template: 'APPENDED'
    },
    ...
```
creates error:
```sh
Invalid modify action (modify must have a pattern or transform function)
```

**Comment by crutchcorn** [comment]
The error itself mentions what's happening here - your `modify` action either needs a `pattern` (which has been commented out in your example) or a `transform` function to modify the values
