### ISSUE TITLE
Support ESM

### ISSUE THREAD

**Issue by stropho** [plopjs/plop#260]
Follow up for https://github.com/plopjs/plop/issues/148
Since 2 years ago, there have been many new things in Node such as support for [ECMAScript modules](https://nodejs.org/docs/latest-v14.x/api/esm.html#esm_interoperability_with_commonjs)
It would be great to enable ESM support, at least to some extent.

Currently `plopfile` exports a function. The easiest workaround :one:  I can think of is for the `plopfile` to export a function or a promise resolving a function. Then the plopfile could look like
```
module.exports = import('./my-esm-plopfile.mjs')
```

:two: Another more robust solution could be 
```
Plop.launch({
	// configPath: argv.plopfile,
	config: thePlopfileFunctionItself
}, run);
```
But after having a brief look on `node-plop`, it seems that this way would be more complicated, most likely a breaking change, because `configPath` is not used only for loading the `plopfile` :thinking: 

:three:  I'm sure there are other options as well :smile: 

What do you think, are the ES modules something worth supporting in `plop` ?

**Comment by crutchcorn** [comment]
PlopJS 3 is releasing this Saturday, with ESM support!

It's stable and has a changelog today ( https://github.com/plopjs/plop/pull/293 ) but won't be launched until Saturday so that, in the event something goes wrong, I can support immediately.

**Comment by crutchcorn** [comment]
ESM modules in Plop are now supported as-of Plop 3!

https://github.com/plopjs/plop/releases/tag/v3.0.0
