### ISSUE TITLE
Run Generator inside actions.

### ISSUE THREAD

**Issue by PinoFlores** [plopjs/plop#263]
I wonder that is was not posible to see the use case of run a generator more dinamic, for example base on conditions on not a linear prompts definition. This remember me like do html and css and not do real programming that one thing that must have is this exactly.

Guys there is a way now to do this? I need to used this lib because some client required me, but I see have a lot of limitations.

Thanks guys.

**Comment by crutchcorn** [comment]
You can use a dynamic actions array to solve this problem

https://plopjs.com/documentation/#using-a-dynamic-actions-array
