### ISSUE TITLE
How to generate n File from a single template, from a prompt that provides a list ?

### ISSUE THREAD

**Issue by afaucogney** [plopjs/plop#273]
I would like to prompt a question about a list of items (view types in my context).
From those view_types, I need to generate a single file, with a specific name that also handle the templating mecanism.

Here is the code I'm trying to run !

```
plop.setGenerator(
	    'popopop',
	     {
    		prompts: [{
                type: "input",
                name: "view_types",
                message: "Type de cellules dans la vue, séparées par une virgule (','):",
                default: "header, item, footer",
                filter: (s) => {
                  // Convert to array.
                  return typeof s === "string"
                    ? s && s.length > 0
                      ? s.split(/,[ ]*/)
                      : []
                    : s;
                }
            }
            ],
    		actions: function(data) {
    		    var actions = [
    		    ]
    		    data.view_types.forEach ( view_type =>
                    actions = actions.concat([
                        {
                            type: 'add',
                            templateFile: 'plop-templates/mvvm/feature/list/res/layout/item_view_type.xml',
                            force: true,
                            path: '../app/src/main/res/layout/item_{{snakeCase view_type}}.xml'
                        }
    		        ])
    		    );
    		    return actions;
    		}
    	});
```

I well see this code cannot work, as {{snakeCase view_type}} is not defined/void !

I expect from the default values "header, item, footer"
- 3 files item_header.xml....
- and that for each file that the {{view_type}} field has been replaced by  corresponding view_type : header, then item, then footer

**Comment by amwmedia** [comment]
You were very close! The issue here is that you are constructing an array of actions that will then be executed within the overall context of the `data` attribute. In this context the `view_type` property doesn't exist, and if it did, it could only be a single value. What you need to do is add data that is available to each action individually. This can be done with the `data` prop that is available for each [action config object](https://plopjs.com/documentation/#interface-actionconfig).

``` javascript
actions = actions.concat([
  {
    type: "add",
    template: "this is a test",
    force: true,
    path: "layout/item_{{snakeCase view_type}}.txt",
    data: { view_type },
  }
]);
```
