### ISSUE TITLE
Quotes and other special characters are replaced with &quot;

### ISSUE THREAD

**Issue by zac-ng** [plopjs/plop#274]
For example, if I try to pass in `<'` as an input like a path, it is processed as `&lt;&quot`;

May be an error occurring when parsing the input, potentially when encoding but I couldn't tell where or if it occurs in the code.

**Comment by crutchcorn** [comment]
This is because of how handlebars is handling escaping. You can solve this with escaping "safely" by passing `<'` with `{{{"<'"}}}`
