### ISSUE TITLE
Input values to PLOP

### ISSUE THREAD

**Issue by scodes11** [plopjs/plop#276]
Is there a way to provide a file as an input to PLOP instead of inputs through prompt? I need to generate a code file using a graphQL file as an input in plop.

**Comment by crutchcorn** [comment]
Sure! Because plopfile.js is simply a JavaScript file, you can do programmatic usage of file reading.

So you could do something like `fs.readFileSync(process.cwd() + "./data.gql")` and then turn that into parsable data.

**Comment by scodes11** [comment]
Thank you for the suggestion but can you point me on how to parse this schema file so that I can access its variables like the "id" variable in given code: 

type Business
{
  id: ID! @aws_cognito_user_pools @auth(rules: [
    { allow: public, operations: [read], provider: iam }
  ])

  owner: String @aws_cognito_user_pools @auth(rules: [
    { allow: public, operations: [read], provider: iam }
  ])
}

**Comment by scodes11** [comment]
Thank you for the suggestion but can you point me how to parse this schema file so that I can access its variables like the "id" variable in the given code :

{
  id: ID! 
  owner: String 
}

**Comment by scodes11** [comment]
Thank you for the suggestion but can you point me how to parse this schema file so that I can access its variables like the "id" variable in the given code :

type Business
@model (subscriptions: { level: off })
@versioned
{
id: ID!
owner: String
}

**Comment by scodes11** [comment]
> Sure! Because plopfile.js is simply a JavaScript file, you can do programmatic usage of file reading.
> 
> So you could do something like `fs.readFileSync(process.cwd() + "./data.gql")` and then turn that into parsable data.

Thank you for the suggestion but can you point me how to parse this schema file so that I can access its variables like the "id" variable in the given code :

type Business
@model (subscriptions: { level: off })
@versioned
{
id: ID!
owner: String
}

**Comment by crutchcorn** [comment]
You'd likely use a library of some kind such as: 

https://www.npmjs.com/package/graphql-tag

**Comment by crutchcorn** [comment]
Glad to hear! :)
