### ISSUE TITLE
Is there a way to set the default case ?

### ISSUE THREAD

**Issue by afaucogney** [plopjs/plop#277]
When we gather a prompt answer, how can we force its case by default ?

Would be much more efficient to be able to define it, because it is often 80% the same case in the template.

That would ensure simpler template most of the time. And in specific case, we can re specify the required case.

**Comment by amwmedia** [comment]
I think I need some context here. I'm not sure what you're asking, sorry.

**Comment by afaucogney** [comment]
Imagine I have a plopjs project that help me to build some Java files.

If the prompt ask me the feature name ?
I can record it in Pascal, Snake, Camel....

Then when I generate the files from the templates, I may build a Class with the feature name, and many other files that import this feature class.

For this I need to specify the case for every templating variables with PascalCase casing.

But in addition, I want to add a file in snakecase format.

At the end I have a single snakecase and maybe 10, 20 camelcase variables.

Today I specify every case format for every templating variables, to secure the fact that the prompt answer may accept every possible case.

What I want, is that I can define the default case formatting, like PascalCase for the feature name.

Like that it will not be required to specify PascalCase in my class and the imports path templating, but just for the file name.

Does it help ?

**Comment by amwmedia** [comment]
Have a look at inquirer's [`filter` function](https://github.com/SBoudrias/Inquirer.js#question). It allows you to process the user's input prior to the actions getting that data. So you could run the input through some formatting logic so you don't need to use helpers everywhere.

**Comment by gnuns** [comment]
@afaucogney you can also use a [dynamic `actions` array](https://plopjs.com/documentation/#using-a-dynamic-actions-array)

```js
 plop.setGenerator("component", {
    description: "A UI Component",
    prompts: [
      {
        type: "input",
        name: "name",
        message: "Component name",
      },
    ],
    actions: (data) => {
      data.Name = plop.getHelper("pascalCase")(data.name);

      return [
        {
          type: "add",
          path: "components/{{Name}}.tsx",
          templateFile: ".templates/component.tsx.hbs",
        },
      ];
    },
  });
```
