### ISSUE TITLE
camelCase does not work with helpers

### ISSUE THREAD

**Issue by neeraj3029** [plopjs/plop#279]
```
{
        type: "add", 
        path: `src/components/test/{{camelCase ComponentNameHelper}}/webpack.config.js`,
        templateFile: "./template/webpack.config.js.hbs",
},
```

Here, the `ComponentNameHelper` returns a string in kebabCase. I want to turn it into camelCase into the path. 
However, {{camelCase ComponentNameHelper}} resolves into empty string.
Is this expected? If yes, is there any workaround to it? Thanks!

**Comment by crutchcorn** [comment]
This should definitely work the way you would expect it to. Are you sure that `ComponentNameHelper` is not `""` somehow?

Closing until we have a more wholistic reproduction
