### ISSUE TITLE
When i try to generate page it crashes

### ISSUE THREAD

**Issue by khaled311** [plopjs/plop#280]
I'm trying to generate page with plop (i have three options : "page", "module", "component") all of them don't work except the "module"

and here is the error:
![Screenshot_6](https://user-images.githubusercontent.com/30202698/130638847-3d636b77-35b7-4e83-a775-614af2fea876.png)

**Comment by crutchcorn** [comment]
I don't think there's enough info to go off of here. Are you able to share that plopfile.js?

**Comment by khaled311** [comment]
Sorry for that, here is the plopfile.js:
`// eslint-disable-next-line
const fuzzyPath = require('inquirer-fuzzy-path');

const requireField = (fieldName) => {
  return (value) => {
    if (String(value).length === 0) {
      return `${fieldName} is required`;
    }
    return true;
  };
};

module.exports = (plop) => {
  plop.setPrompt('fuzzyPath', fuzzyPath);

  // get module name from path
  plop.setHelper('moduleName', (text) => {
    return text.split('/')[1];
  });

  plop.setGenerator('module', {
    description: 'Create a module',
    prompts: [
      {
        type: 'input',
        name: 'name',
        message: 'What is your module name?',
        validate: requireField('name'),
      },
      {
        type: 'input',
        name: 'pageName',
        message: 'What is the name of your main page?',
        validate: requireField('pageName'),
      },
    ],
    actions: [
      // main page
      {
        type: 'add',
        path:
          'src/{{camelCase name}}/pages/{{pascalCase pageName}}/{{pascalCase pageName}}.tsx',
        templateFile: 'plop-templates/Page/Page.ts.hbs',
      },
      {
        type: 'add',
        path:
          'src/{{camelCase name}}/pages/{{pascalCase pageName}}/{{pascalCase pageName}}.module.scss',
        templateFile: 'plop-templates/Page/Page.module.scss.hbs',
      },
      {
        type: 'add',
        path: 'src/{{camelCase name}}/pages/{{pascalCase pageName}}/index.ts',
        templateFile: 'plop-templates/Page/index.ts.hbs',
      },
      //wrapper
      {
        type: 'add',
        path: 'src/{{camelCase name}}/index.tsx',
        templateFile: 'plop-templates/Wrapper/Page.ts.hbs',
      },
      // {
      //   type: "add",
      //   path:
      //     "src/{{camelCase name}}/pages/{{pascalCase name}}Wrapper/{{pascalCase name}}Wrapper.module.scss",
      //   templateFile: "plop-templates/Wrapper/Page.module.scss.hbs",
      // },
      // {
      //   type: "add",
      //   path:
      //     "src/{{camelCase name}}/pages/{{pascalCase name}}Wrapper/index.js",
      //   templateFile: "plop-templates/Wrapper/index.js.hbs",
      // },
      //router
      {
        type: 'add',
        path: 'src/{{camelCase name}}/routes.ts',
        templateFile: 'plop-templates/Routes/Routes.ts.hbs',
      },
      {
        type: 'add',
        path: 'src/{{camelCase name}}/utils/path.js',
        templateFile: 'plop-templates/Routes/Path.js.hbs', //check again
      },
      {
        type: 'append',
        path: 'src/app/utils/path.js',
        pattern: `/* inject module path import */`,
        template: `import { {{camelCase name}}Path as {{camelCase name}} } from '{{camelCase name}}/utils/path';`,
      },
      {
        type: 'append',
        path: 'src/app/utils/path.js',
        pattern: `/* inject module path */`,
        template: `  {{camelCase name}},`,
      },
      {
        type: 'append',
        path: 'src/app/routes.ts',
        pattern: `/* PLOP_INJECT_MODULE_ROUTES_IMPORT */`,
        template: `const {{pascalCase name}} = React.lazy(() => import("{{camelCase name}}"));`,
      },
      {
        type: 'append',
        path: 'src/app/routes.ts',
        pattern: `/* PLOP_INJECT_MODULE_ROUTES */`,
        template: `
    {
      path: "/{{dashCase name}}",
      component: {{pascalCase name}}
    },`,
      },
      // Store
      {
        type: 'add',
        path: 'src/{{camelCase name}}/store/index.js',
        templateFile: 'plop-templates/Store/index.js.hbs',
      },
      {
        type: 'add',
        path: 'src/{{camelCase name}}/store/actions.js',
        templateFile: 'plop-templates/Store/actions.js.hbs',
      },
      {
        type: 'add',
        path: 'src/{{camelCase name}}/store/types.js',
        templateFile: 'plop-templates/Store/types.js.hbs',
      },
      {
        type: 'add',
        path: 'src/{{camelCase name}}/store/sagas.js',
        templateFile: 'plop-templates/Store/sagas.js.hbs',
      },
    ],
  });

  plop.setGenerator('component', {
    description: 'Create a component',
    prompts: [
      {
        type: 'input',
        name: 'compName',
        message: 'What is your component name?',
        validate: requireField('compName'),
      },
      {
        type: 'fuzzyPath',
        name: 'modulePath',
        message: 'in which module will your component live?',
        itemType: 'directory',
        rootPath: 'src/',
        depthLimit: 0,
        excludeFilter: (nodePath) => nodePath === 'src/',
        validate: requireField('modulePath'),
      },
    ],
    actions: [
      {
        type: 'add',
        path:
          '{{modulePath}}/components/{{pascalCase compName}}/{{pascalCase compName}}.tsx',
        templateFile: 'plop-templates/Component/Component.ts.hbs',
      },
      {
        type: 'add',
        path:
          '{{modulePath}}/components/{{pascalCase compName}}/{{pascalCase compName}}.module.scss',
        templateFile: 'plop-templates/Component/Component.module.scss.hbs',
      },
      {
        type: 'add',
        path:
          '{{modulePath}}/components/{{pascalCase compName}}/{{pascalCase compName}}.test.js',
        templateFile: 'plop-templates/Component/Component.test.js.hbs',
      },
      {
        type: 'add',
        path: '{{modulePath}}/components/{{pascalCase compName}}/index.ts',
        templateFile: 'plop-templates/Component/index.ts.hbs',
      },
    ],
  });

  plop.setGenerator('page', {
    description: 'Create a page',
    prompts: [
      {
        type: 'input',
        name: 'pageName',
        message: 'What is your page name?',
        validate: requireField('pageName'),
      },
      {
        type: 'fuzzyPath',
        name: 'modulePath',
        message: 'in which module will your component live?',
        itemType: 'directory',
        rootPath: 'src/',
        depthLimit: 0,
        excludeFilter: (nodePath) =>
          nodePath === 'src/' || nodePath === 'src/app',
        validate: requireField('modulePath'),
      },
    ],
    actions: [
      {
        type: 'add',
        path:
          '{{modulePath}}/pages/{{pascalCase pageName}}/{{pascalCase pageName}}.tsx',
        templateFile: 'plop-templates/Page/Page.ts.hbs',
      },
      {
        type: 'add',
        path:
          '{{modulePath}}/pages/{{pascalCase pageName}}/{{pascalCase pageName}}.module.scss',
        templateFile: 'plop-templates/Page/Page.module.scss.hbs',
      },
      {
        type: 'add',
        path:
          '{{modulePath}}/pages/{{pascalCase pageName}}/{{pascalCase pageName}}.test.js',
        templateFile: 'plop-templates/Page/Page.test.js.hbs',
      },
      {
        type: 'add',
        path: '{{modulePath}}/pages/{{pascalCase pageName}}/index.js',
        templateFile: 'plop-templates/Page/index.ts.hbs',
      },
      {
        type: 'append',
        path: '{{modulePath}}/utils/path.js',
        pattern: `/* inject path */`,
        template: `  {{constantCase pageName}}: '/{{moduleName modulePath}}/{{dashCase pageName}}',`,
      },
      {
        type: 'append',
        path: '{{modulePath}}/routes.ts',
        pattern: `/* PLOP_INJECT_PAGE_IMPORT */`,
        template: `const {{pascalCase pageName}} = React.lazy(() => import('./pages/{{pascalCase pageName}}'));`,
      },
      {
        type: 'append',
        path: '{{modulePath}}/routes.ts',
        pattern: `/* PLOP_INJECT_PAGE_ROUTE */`,
        templateFile: 'plop-templates/Routes/Route.ts.hbs',
      },
    ],
  });
};
`

**Comment by crutchcorn** [comment]
This issue is because of a custom usage of `inquirer-fuzzy-path`. You can use the `inquirer` prop inside of a `prompt` to solve this bug, as described here: #121 

Related issue: #316
