### ISSUE TITLE
Is there any hook that we can run after the file generation

### ISSUE THREAD

**Issue by afaucogney** [plopjs/plop#282]
Let's imagine I have a generator with a lib, that we need to import in many files. In my case this is RxJava3.
So I have some import like this in java :

    import io.reactivex.rxjava3.core.Observable

Now, for a single project that not yet use RxJava3, but still RxJava2, with the following import :

    import io.reactivex.Observable

I do not want to add a {{if}} mechanisms just for this, because I want to keep the file simple ! 
Additionally, it will probably be removed in a couple of months, years to migrate to RxJava3.

So my question, is there a way, to get the generate file in a a kind of stream, or lambda, and then apply update with a script ?

In my case, I would simply replace the first string by the second one if a condition is true ?

If someone has another solution for my problem, feel free to post it !

**Comment by benhickson** [comment]
What's the condition you're testing to see if true? Where is that value located/provided?

**Comment by afaucogney** [comment]
Hi, the condition could come from the prompt ! 

Eg : do you want to migrate to rxjava2 ? True/false.

**Comment by benhickson** [comment]
This sounds it'd fit your needs:
https://github.com/plopjs/plop#using-a-dynamic-actions-array

**Comment by crutchcorn** [comment]
It indeed does sound like a dynamic array would solve the problem here. Feel free to re-open if it did not solve your problem
