### ISSUE TITLE
Cannot bypass `list` prompt when its value is an object

### ISSUE THREAD

**Issue by knikolov-nuvolo** [plopjs/plop#284]
I have a `list` prompt, and each item in the list has an object set for its value, e.g.:

```js
{
  type: 'list',
  name: 'folder',
  message: 'Select folder:',
  choices: [
    {
      name: 'components',
      short: 'components',
      value: {
        name: 'components',
        relativePath: './src/components',
        absolutePath: '/Users/knikolov/Projects/my-project/src/components',
      },
    },
    {
      name: 'test',
      short: 'test',
      value: {
        name: 'test',
        relativePath: './test',
        absolutePath: '/Users/knikolov/Projects/my-project/test',
      },
    },
  ]
}
```

When I try to bypass that prompt with any of these, it fails.
```
plop template 0
plop template components
```

After debugging, I found out that the reason is because of this line:
https://github.com/plopjs/node-plop/blob/1c09ef314eed9f16a8071a2870c6df472201be02/src/prompt-bypass.js#L27

Here, it expects that the `value` is always string and tries to call `toLowerCase()` without checking its type.
If we add `typeof choiceValue === 'string'` it should be possible to match choice values by name and/or index.

As a temporary solution I added `toLowerCase: () => name` to the value (which is an ugly solution).

**Comment by crutchcorn** [comment]
Oh, this is a good catch! 

Thanks for looking into the code to find the solution - that would've taken me a while, admittedly. 

Your solution of `typeof == 'string'` seems like a great solution to me. Any chance you'd want to open a PR? :)

**Comment by knikolov-nuvolo** [comment]
@crutchcorn 
PR created: [node-plop/pull/209](https://github.com/plopjs/node-plop/pull/209) :)
