### ISSUE TITLE
What's the best way to add a line only if it doesn't exist?

### ISSUE THREAD

**Issue by benhickson** [plopjs/plop#285]
Ideally we'd have a ActionConfig key like `patternNotExist` alongside `pattern` so that when appending a line, it would append it after the matched `pattern`, but only if the regex in `patternNotExist` finds zero matches in the file `path`.

Use case: I need to add a particular import, but I can only add it once. I'm using plop to generate resources in an ongoing repo.

**Comment by crutchcorn** [comment]
@benhickson you should be able to pass a `skip` function that in turn uses a regex and a conditional on said regex. 

Please feel free to re-open this issue if that does not solve your problem
