### ISSUE TITLE
[TS] adjust type definition of `run` to be async, aka, return Promise<void>

### ISSUE THREAD

**Issue by Pike** [plopjs/plop#295]
https://github.com/plopjs/plop/blob/f1ef61d8661458da08e6a89c0e6c7cd61d321649/src/plop.d.ts#L17 says that `run` is sync, but it's now an async method.

Should return a `Promise<void>` right now?

**Comment by crutchcorn** [comment]
Whoops! You're 100% right. I was so busy updating the Liftoff and `node-plop` typings that I forgot about `run` 😅 I'll cut a new release right now

**Comment by crutchcorn** [comment]
Release 3.0.1 fixes this! Made the commit with you as co-author, since you basically did the code fix with the suggestion of `Promise<void>` anyway :) 

https://github.com/plopjs/plop/commit/744999399a3bc9252ff42e67abbad4778d025529
