### ISSUE TITLE
Doc issue: The link throws a 404 error

### ISSUE THREAD

**Issue by atapas** [plopjs/plop#306]
The link mentioned [in this doc section](https://plopjs.com/documentation/#custom-action-function-) results in a 404

![image](https://user-images.githubusercontent.com/3633137/147418169-edeb0d8b-d4b2-4c63-a77e-37a32fe66d54.png)

The target link: https://github.com/plopjs/plop/blob/master/example/plopfile.js

**Comment by crutchcorn** [comment]
Oh, that's right! I forgot to update this!

The link should point here:

https://github.com/plopjs/plop/blob/master/tests/examples/javascript/plopfile.js

Would you like to make a PR to be listed as a contributor? :D

**Comment by atapas** [comment]
Oh yes. Will get it done in a couple of days 😀.

**Comment by atapas** [comment]
@crutchcorn Could you please assign this issue to me? I have fixed it and am about to raise a PR.

**Comment by atapas** [comment]
Raised the PR: https://github.com/plopjs/plop/pull/309

Thanks!

**Comment by atapas** [comment]
Hey @crutchcorn 

Thanks for merging the PR. Will I be added to the list of excellent contributors to this fabulous project? Just curious 😀
