### ISSUE TITLE
pass a json problem?

### ISSUE THREAD

**Issue by vuejstime** [plopjs/plop#307]
hello currently a'm trying to write some thing like this http://json2ts.com/ for my local cli using plop.
the problem is how to get json data in command line or even a json file from my local project?
when i pase the json to comman it will execute but the json not passed

**Comment by crutchcorn** [comment]
I apologize, I don't follow, but I also think this usage may be somewhat fringe for usage in Plop.

Could you link a repo repro for me to take a look at?

**Comment by vuejstime** [comment]
my repo is not open source but here is the plop code :
```
const JsonToTS = require("json-to-ts");
 const config = (plop) => {
  plop.setHelper("interfaceFromJson", function (json) {
    return JsonToTS(json).join("\n");
  });
  plop.setGenerator("interface", {
    description: "create an interface for my app",
    prompts: [
      {
        type: "input",
        name: "name",
        message: "name of your module you want generate interface for it?",
      },
      {
        type: "input",
        name: "json",
        message: "paste your json here?",
      },
    ],
    actions: [
      {
        type: "add",
        path: "src/composables/{{camelCase name}}/{{pascalCase name}}.interface.ts",
        templateFile: "plop-templates/interface.hbs",
      },
    ],
  });
}
```
and this is my templete code `.hbs`
```
{{interfaceFromJson json}}

```
it works perfectly when i set a test json to the helper and every thing work as expected, like this
```
  plop.setHelper("interfaceFromJson", function () {
      const json = {
      cats: [
        {name: 'Kittin'},
        {name: 'Mittin'}
      ],
      favoriteNumber: 42,
      favoriteWord: 'Hello'
    }
    return JsonToTS(json).join("\n");
  });
  ```
  but the problem is i can not get json from terminal

**Comment by vuejstime** [comment]
however i solved my problem with putting json file in local files and get only name in command not entire json
