### ISSUE TITLE
Running custom code after plop generator

### ISSUE THREAD

**Issue by atulpatildbz** [plopjs/plop#310]
Hi.
I wanted to know if there is a way to run a custom nodejs code after plop generator has ran. 

I need this for "sanitizing" the generated files. Formatting and linting it appropriately.

**Comment by atulpatildbz** [comment]
Found out about `transform` property in action. Closing the issue.

**Comment by natterstefan** [comment]
Hi @atulpatildbz,

sorry for commenting in a closed issue, but can you please provide an example of how you managed to do this? Thanks a lot.

**Comment by natterstefan** [comment]
Hi @atulpatildbz,

can you please tell me how you achieved this? I am trying to use ESLint to lint the output after the generators are finished.
