### ISSUE TITLE
use in multiple projects

### ISSUE THREAD

**Issue by ziaadini** [plopjs/plop#311]
Hi,
the problem i faced is i'm using plop for multiple projects and my source code destributed in multiple places.
is there any way to write modules or pack our custom code generators to npm?
or move `plopfile.js` file from root of project to a sub folder and control it's versions with git?

**Comment by amwmedia** [comment]
yes, all plop constructs (generators, helpers, actions, etc) can be packaged up into a project and imported using `plop.load` details can be found in [this MD document](https://github.com/plopjs/plop/blob/master/plop-load.md)
