### ISSUE TITLE
Validate function not working!?

### ISSUE THREAD

**Issue by branquito** [plopjs/plop#312]
Somehow I cannot get `validate()` function to work, in prompts array:

Having this set as one of those prompt inquire-like objects inside my `plopfile.js` config file:

``` 
     {
        type: "list",
        name: "api",
        message: "Which API would you like to use?",
        choices: ["Options API", "Composition API"],
        filter: (value) => {
          return `api set to: ${value.toUpperCase()}`;
        },
        validate(value) {
          console.log({ value });
          return "NO PASARAN!!!";
        },
      },
```

`filter()` is working fine here, as I can see the transformed value in my `.hbs` rendered files, however I cannot get the output of `console.log` statement printed out from `validate()` function

This is the output I am getting, so it is successful, despite the fact that the `validate()` should break the chain, after returning an error message!?

```
? Which API would you like to use? Composition API
{
  answers: { name: 'MyGreatVueComponent', api: 'api set to: COMPOSITION API' }
}
✔  +! 3 files added
 -> /src/components/MyGreatVueComponent/a.txt
 -> /src/components/MyGreatVueComponent/b.txt
 -> /src/components/MyGreatVueComponent/c.txt
```

I have also tried with `validate()` being an `async` function as well, without success

### Edit:
I have just found out, that while it does not work for `type: "list"`, the same `validate` function works for `type: "input"`, maybe that can help

### Edit No 2:
After looking at the Inquirer docs, I see that list type does not include validation as option, so I guess it is because of that that validation doesn't work in this case. I will close the issue, but maybe keep this one as a reference if someone gets into similar situation
<img width="737" alt="image" src="https://user-images.githubusercontent.com/1226132/154937902-54e173a9-4e5e-44e9-871c-15d521a3b4f6.png">

**Comment by stetsmando** [comment]
Helpful, thank you @branquito
