### ISSUE TITLE
Trouble with async/await

### ISSUE THREAD

**Issue by rexkenley** [plopjs/plop#314]
Hi

I am having trouble trying to create an async function as a setActionType. Can you please provide an example?

I have a function that creates a project folder and runs the npm i command. I noticed that if I used synchronous, the spinner stops spinning. It works but the ui might give the impression that the process hanged.

Thanks.

**Comment by crutchcorn** [comment]
Currently, `actionType` cannot be an async function. This issue is made as a tracker on current progress in that area:

#242
