### ISSUE TITLE
[Plop3] Problem to use inquirer-autocomplete-prompt 2.0.0

### ISSUE THREAD

**Issue by Sulfuin** [plopjs/plop#316]
Hello,

with plop v3.0.5 and inquirer-autocomplete-prompt v2.0.0 it's impossible to me to use 'autocomplete' as prompt.

I have an error [ERROR] dest.addListener is not a function and i don't have a trick to resolve it.

Someone could help me here?

Thanks all!

**Comment by amwmedia** [comment]
It looks to me like you might need to tap into inquirer's reactive API. This is described in issue #121.
