### ISSUE TITLE
[Questions] Multiple plop files and npx integrationg

### ISSUE THREAD

**Issue by rexkenley** [plopjs/plop#318]
Hi

Can Plop have multiple plopfile? I want to create multiple plop files that is specific to a part of my project instead of having 1 huge plopfile that covers the entire project.

Is it possible to call plop from npx? 

i.e. npx myProject plop addProject 

Thanks

**Comment by amwmedia** [comment]
Yes, multiple plopfiles can be created. You can have a different plopfile per folder and plop will locate the one "closest" to your CWD when it runs. If you want them to be all in the same directory, you could use the `--plopfile` flag to specify which file you'd like to run.

As far as NPX goes, I'm not sure. I've never tried to do such a thing.

**Comment by rexkenley** [comment]
Thank you.
