### ISSUE TITLE
Support for different embedded templates (like `ejs`)

### ISSUE THREAD

**Issue by marcelmokos** [plopjs/plop#321]
Can I work on a PR that would add an option to change templating language from `handlebars` to `ejs` possibly other templating languages?

I am a user of `plop` ❤️ on many projects but I feel limited by `handlebars` templates and helpers. I would prefer to use Javascript as `ejs` allows. 
- https://github.com/mde/ejs

I do not want to create a similar library with different templating language when I like and use `plop` on my projects.

**Comment by crutchcorn** [comment]
Closing in favor of #10, which describes the method of which we'd implement EJS support
