### ISSUE TITLE
stripExtensions doesn't work with dot files

### ISSUE THREAD

**Issue by rwacarter** [plopjs/plop#324]
I have, for example, a folder with a `.babelrc` and a `package.json` file in it. However, I'd like to pass some values into these files so I rename them `.babelrc.hbs` and `package.json.hbs` respectively. 

Then when using them as `templateFiles` with an `addMany` action, the `package.json` file is correctly renamed but the `.babelrc.hbs` still has the `hbs` suffix. 

Unless I'm missing something, this is hopefully solved by adding a simple check to the `stripExtensions` function, to make sure hidden files are included. I'd be happy to look into this and submit a pull request if that's the case.

**Comment by oneezy** [comment]
appreciate the fix @knikolov-nuvolo , this solved my issue
