### ISSUE TITLE
Example usage to improve the type declarations

### ISSUE THREAD

**Issue by cspotcode** [plopjs/plop#325]
I wrote a sample use-case of someone using the plop API.  I hope it can drive improvements to the type declarations.  The declarations are meant to serve users, to make it possible to write plopfiles quickly without having the plop API memorized.  This example will hopefully make the issues a bit clearer.

This example shows a user trying to declare and use a custom action type.  I added comments pointing out some of the changes we'll need to make.

The new sandbox pulls in types automatically, so it'll show meaningful errors and tab completion based on plop's current declarations.

[TypeScript sandbox](
https://www.staging-typescript.org/play?#code/JYWwDg9gTgLgBAbzgOQgEwKYAUA2EwCCWAkgDRwEDGMwEAdgML0BmwA5nAL5zNQQhwA5HXQYAtGDxhBAbgCwAKEUB6ZXAAyGeAFcAzhii64wOrpgBDHDjgwAFsCPnqtOnEot2xujAhxJ+QSMYAE8wDF1FExgDZicMOAY9HxAqGnomOlYODAAPaLo0I1SXDKzERThKm1CMAC4hSiT+MSc0ulkKqsazfgAxYAwcNHq6bRAAIwN5BU5FRVzIWDhMWO0ceGZtOmd6Nw82AAp-MHrUTFx8ImIASnKFSuOAOn0YYvoAFRqDwW7klp32uRzLpgts4AdzKYAO4GXTkdyZdjkY63AC8AD47lU4Ko4AB1WzBODmKDxBFlSFoPxSPwQXS6YDjHBErYrEwYNAAfkqBPMOn0YkowPiDhs9iM+igADcTGxuXALmA4FDgFZiTgoeZgkYwMCjABmYlQNhjDDeOFwKDsWwwTlze5dehmRC-PoDIbcVF7RFsGQ4tTIDAc4lwSYwaJQZVanjQPwYfA4eI+Za+OwOR6dSq4gCqkoltggaypk2JTKTvl0YUowGYRLsSZqcAgzG9WXIscT5ilIvgaFB5hAwEomf9ytsZrFGCJaHogngdCDVPr1TCukelXe47gbAglmMRmYseOgRX4RsvhA5gA1hgR7jgPAMMCBpHk3ok1vjhQSMqHwXtPAthdrKxjwCAGAgNAwAAF4cuucDEPAuj-kMd5qCI8AlgAVEBUCYFAWExpG76GOecDvpOwCRhAUKuLk+QMk6GZKA6WZqAABokPQpACvRbAC7FwMhhZDKGSYwtewbjMKVK7KSe56OYbDxLq4YGKYzHYriWB8NJTJEsJRZiW4QF0MpS6+OY25mgYQ61GhcCcU0PFtHx2xtAAPKUnj0WahQUAC3kcF6kLBOiELQrC9QQOMABWGDUPC+z1EFyJSKcoiKlcaKYmYVpmXAAA+cBShAwBUsVOn8A4GAeXlIHFaV5Xoux9rYqSMDaFAriCLIo4eWIYi-nYhbwB1XV0CBVn1WZ5AwtZ8BWSEYRwAYfBQPBeLxCASSWloE0hjNbDwcQQTinAC6UOEugksEdoOpw1zTJ0TwvAA4jZUB8tA3wzoKzn-G0gjkAgI6tC4uj1AA2qDrFVMtdQNAD4OzuQuIDUNNbkXmyoGPE5hlmRJhmJY1j1lRbjIwCp6OOMEDduQ9auGmRhQiJS4E4K-CSFoZLQKS1DMpp2KU9x-SDMMcAAIwAEz6iOnAALqdI90ycEAA)

**Comment by crutchcorn** [comment]
Closing, since `node-plop` definitions have been improved to the point where your sandbox now no longer throws any problems (outside of the custom config, which has been documented)
