### ISSUE TITLE
runActions and runPrompts required by types definition. No example in the doc

### ISSUE THREAD

**Issue by adelin-b** [plopjs/plop#339]
Hello, thoses two types are required by `PlopGenerator` however everything works fine when they are not set.
```ts
export interface PlopGenerator extends PlopGeneratorConfig {
	runPrompts: (bypassArr?: string[]) => Promise<any>;
	runActions: (
		answers: any,
		hooks?: PlopActionHooks
	) => Promise<{
		changes: PlopActionHooksChanges[];
		failures: PlopActionHooksFailures[];
	}>;
}
```

you could expose `import { PlopGeneratorConfig } from 'plop/node_modules/node-plop'` directly from `plop`

**Comment by crutchcorn** [comment]
Makes sense to me! 

This should be a single-LOC change [here](https://github.com/plopjs/plop/blob/main/packages/plop/src/plop.d.ts#L3-L14). Would you like to do the honors by opening a PR in order to be included in the CHANGELOG? :)

**Comment by naiknareshh** [comment]
I see there has not been any progress on this one since a long time. do you mind if I pick this up? @crutchcorn

**Comment by crutchcorn** [comment]
Go for it @naiknareshh !
