### ISSUE TITLE
Undisclosed breaking change?

### ISSUE THREAD

**Issue by daniel-ac-martin** [plopjs/plop#340]
Has there been an undisclosed breaking change in the `node-plop` package?

I'm trying to upgrade to the latest version, and it looks like `plop.load()` is now an `async` function so I now need to call it with `await`.

**Comment by crutchcorn** [comment]
Not undisclosed - this was an intentional change that was part of our CHANGELOG as part of the 0.30.0

**Comment by daniel-ac-martin** [comment]
Ah okay. Sorry for missing it @crutchcorn.

**Comment by crutchcorn** [comment]
No worries!
