### ISSUE TITLE
Can't bypass a checklist prompt without selecting at least one option

### ISSUE THREAD

**Issue by bradgarropy** [plopjs/plop#345]
### _[Example Repo](https://github.com/bradgarropy/plop-issue)_

# Bypassing Checklist Prompts With No Options Selected

I created a minimal reproduction of the issue by creating a `pizza` generator where you select from three possible toppings.

The goal is to be able to bypass the `checklist` prompt and select none of the toppings.  
Or in pizza terms, I want to order a cheese pizza. 🍕

```
npm run plop

? Choose your toppings. (Press <space> to select, <a> to toggle all, <i> to invert selection, and <enter> to proceed)
>( ) pepperoni
 ( ) sausage
 ( ) onions
```

# PASS

```
npm run plop pepperoni

✔  -> {"toppings":["pepperoni"]}
```

# PASS

```
npm run plop pepperoni,sausage,onions

✔  -> {"toppings":["pepperoni","sausage","onions"]}
```

# FAIL

In this case, I would expect to be able to bypass the `checklist` prompt by including something like an empty string (`""`) or an empty array (`[]`).

```
npm run plop ""

✔  -> {"toppings":[]}
```

**Comment by JSDUNIYA** [comment]
May you need to hide toppings with `when:false` property based on previous value selected.

**Comment by bradgarropy** [comment]
In my actual use case, the prompt in question doesn't rely on previous prompts, much like this pizza example.

**Comment by bradgarropy** [comment]
Thanks for pointing me in the right direction @amwmedia, I'll get a pull request up soon!

**Comment by bradgarropy** [comment]
I opened #354 to address this issue, I hope it covers the use case!

/cc @amwmedia @crutchcorn
