### ISSUE TITLE
Help: how to load() from a file or npm package

### ISSUE THREAD

**Issue by tatimblin** [plopjs/plop#349]
I am having trouble setting up my external plopfiles for plop.load(), and would like some help.

These are my configuration files right now

./plopfile.js
```
const config = (plop) => {
  plop.load("./plopfiles/component.js");
  plop.load("my-package");
};

export default config;
```

./plopfiles/component.js
```
const config = (plop) => {
  plop.setDefaultInclude({ generators: true });

  plop.setGenerator('basics', {
    description: 'this is a skeleton plopfile',
    prompts: [],
    actions: [
      {
        type: 'add',
        path: `SUCCESS.md`,
        templateFile: `README.md`,
      }
    ]
  });
}

export default config;
```

node_modules/my-package/index.js
```
const config = (plop) => {
  plop.setDefaultInclude({ generators: true });

  plop.setGenerator('basics2', {
    description: 'this is a skeleton plopfile',
    prompts: [],
    actions: [
      {
        type: 'add',
        path: `SUCCESS2.md`,
        templateFile: `README.md`,
      }
    ]
  });
}

export default config;
```

I would expect this to work, but the generators are not found (`[PLOP] No generator found in plopfile`). Does anyone have experience using `plop.load()` with es6 modules, and know how the exports should be setup?

Happy to add any other information! Thank you

**Comment by tatimblin** [comment]
I've also tried following the few plop repos created by @bradgarropy

https://github.com/bradgarropy/plop-helper-slugify/blob/master/index.js

```
const test = (plop) => {
  plop.setDefaultInclude({ generators: true });

  plop.setGenerator('basics', {
    description: 'this is a skeleton plopfile',
    prompts: [],
    actions: [
      {
        type: 'add',
        path: `SUCCESS.md`,
        templateFile: `README.md`,
      }
    ]
  });
}

module.exports = test;
```

**Comment by bradgarropy** [comment]
Hey @tatimblin,
I have yet to move any of my `plop` stuff over to `esmodules`, I've run into some issues there. If you export your `plop` generators as `commonjs` does that work?

As far as the `es6` support, [here](https://plopjs.com/documentation/#3-create-a-plopfilejs-at-the-root-of-your-project) is what the documentation has to say.

> `export default` is only allowed in NodeJS inside "ESM" supported files. To use this syntax, your `plopfile` must be either:
> 
> An ESM .js file with type: "module" in package.json
> An ESM .mjs file with any type declared in package.json
> 
> Alternatively, you can have a `plopfile` with `module.exports = function (plop)` instead. For this syntax, your `plopfile` must be either:
> 
> A CommonJS .js file with type: "commonjs" in package.json
> A CommonJS .cjs file with any type declared in package.json

Can you try naming the file `plopfile.mjs` or updating the `type` in your `package.json`?

**Comment by tatimblin** [comment]
Thanks for the reply :)

If I set them to commonjs (`"type": "commonjs"`), I noticed I am able to `console.log(plop)` in the loaded file and see the output! Unfortunately the generators being set in that function do not get recognized. In my first post you can see I have `plop.setDefaultInclude({ generators: true });` I also tried removing, and setting all to true `plop.load('./plopfiles/component.js', {}, true);` from the [docs](https://github.com/plopjs/plop/blob/main/plop-load.md#:~:text=plop.load('.%2Fplopfiles%2Fcomponent.js'%2C%20%7B%7D%2C%20true)%3B).

**Comment by bradgarropy** [comment]
From what I understand in the documentation, `setDefaultInclude` should be executed inside of `plopfiles/component.js`. It's a way for an external `plopfile` to declare what should be included.

Can you try modifying `plopfiles/component.js` to the following:

```
module.exports = function (plop) {
  console.log('hey - component.js')

  plop.setDefaultInclude({generators: true})

  plop.setGenerator('basics', {
    description: 'this is a skeleton plopfile',
    prompts: [],
    actions: [
      {
        type: 'add',
        path: `SUCCESS.md`,
        templateFile: `README.md`,
      }
    ]
  });

  plop.setGenerator('basics2', {
    description: 'this is a skeleton plopfile',
    prompts: [],
    actions: [
      {
        type: 'add',
        path: `SUCCESS.md`,
        templateFile: `README.md`,
      }
    ]
  });

  console.log(plop.getGeneratorList(), 'nested');
}
```

Also, if you'd like a full fledged example of how I write `plop` generators, take a look at [plop-generator-react-component](https://github.com/bradgarropy/plop-generator-react-component).

**Comment by tatimblin** [comment]
Thank you again for your assistance. I was looking through that and some of your other plop repos (cool personal website btw!), today I noticed that you're on plop 2.7.4. I downgraded and everything worked!

If you're greater repo is es6 like mine:
1. downgrade to `2.7.4`
2. use commonjs by changing file name to plopfile.cjs
3. update npm script to `plop  --plopfile plopfile.cjs`

Sounds like there is a bug in version 3 that appears to be a race condition. The plop cli prompt is triggered before external generators can be loaded in.

**Comment by bradgarropy** [comment]
I think you're right, I've never upgraded to v3 due to these types of issues. Maybe @crutchcorn or @amwmedia can come in and give their opinions. Otherwise, I think chilling at v2 is a good choice.

Thanks for the compliment on my website, yours is pretty cool as well!

**Comment by crutchcorn** [comment]
@tatimblin `plop.load` is now async with v3 IIRC (on mobile right now)

Could you try this and let me know if it works? 

```
const config = async (plop) => {
  await plop.load("./plopfiles/component.js");
  await plop.load("my-package");
};

export default config;
```

**Comment by tatimblin** [comment]
@crutchcorn yes that was it!

```
export default async (plop) => {
  await plop.load("@yext/sites-react-starters");
};
```

works fine :)

**Comment by imbarwinata** [comment]
> 

Works well at my place too, thanks @crutchcorn 🎉
