### ISSUE TITLE
Generators do not work with plop.load()

### ISSUE THREAD

**Issue by SmartMointy** [plopjs/plop#377]
Generators that are loaded with plop.load() don't work.

Example: https://stackblitz.com/edit/node-pgpt6w

_generators.js_
```javascript
const myGenerators = (plop) => {
  plop.setGenerator('myTestGenerator', {
    description: 'this is just a test',
    prompts: [
      {
        type: 'input',
        message: 'Enter your name',
        default: 'Pete',
      },
    ],
    actions: [],
  });
};

module.exports = myGenerators;
```

_plopfile.js_
```javascript
const myPlop = (plop) => {
  plop.load('./generators.js', {}, { generators: true });
};

module.exports = myPlop;
```

### Expected Behavior 
The generator `myTestGenerator` within `./generators.js` should run, as it is the only generator. 

### Actual Behavior
Error message: `[PLOP] No generator found in plopfile`

**Comment by sayjeyhi** [comment]
+1

**Comment by JamesBarrettDev** [comment]
```
const myPlop = async (plop) => {
  await plop.load('./generators.js', {}, { generators: true });
};

module.exports = myPlop;
```

**Comment by crutchcorn** [comment]
@sayjeyhi please do not leave `+1` or tag me (or other maintainers).

As for this issue, @JamesBarrettDev is correct - you'll need to `await` `plop.load`
