### ISSUE TITLE
Supporting plopfile.ts .ts extension

### ISSUE THREAD

**Issue by WildOsk** [plopjs/plop#416]
I have read some threads on github about this but i dont get what to do.

I receive the following error you already know:

[PLOP] Something went wrong with reading your plop file TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts"

**Comment by David-Tsui** [comment]
You can compile it to js manually.
the `module` option might different between repos. If not working, please refer to ts compiler options.

```
tsc --module nodenext ./plopfile.ts --outDir . && prettier --write ./plopfile.js
```

**Comment by WildOsk** [comment]
But i guess at some point this will be supported natively(?) without needing to compile it first?

**Comment by amwmedia** [comment]
I think @crutchcorn has done quite a bit of work on getting this working. I believe it's close.

**Comment by WildOsk** [comment]
Good to know it's close @amwmedia

**Comment by ryparker** [comment]
Could we keep this issue open for tracking/notification purposes?

**Comment by crutchcorn** [comment]
Apologies, closing as a dupe of #297
